#!/usr/bin/env node
(function (hook) {
	if (!hook) return;
	try {
		hook
		.split(require("path").delimiter)
		.map(require)
		.pop()
		.call(null, "pre-receive");
	}
	catch (err) {
		process.exit(1);
	}
})(process.env.EXPRESS_GIT_HOOK);
